@startuml stateapp
!include themes/puml-theme-cerulean-outline.puml

skinparam backgroundColor #FFFFFF
skinparam scale 100
skinparam dpi 100
skinparam state {
    AttributeFontColor Black
    BackgroundColor AliceBlue
}
[*] -right-> NotRegistered : The user is not registered.
[*] -right-> Registered : The user is registered.

state NotRegistered {
    NotRegistered : The user is not registered, limited functions.
    [*] -right-> initialNotRegistered
    state "Not Registered Main Screen" as initialNotRegistered
    state "Initial Login State" as login
    state "Bad Login State" as bad_login
    state RegisterScreen

    initialNotRegistered : The user must search and see publications
    initialNotRegistered : The user can press a publication.
    initialNotRegistered : The user can press the button to log in and register
    initialNotRegistered : The down-menu is disabled as the user is not already logged in

    initialNotRegistered --> login : Press button of the image profile
    login --> initialNotRegistered : Go Back button
    login: The user can press a button to go to register page if it is not already registered.
    login : The user put the username and password to enter

    login -> bad_login : User or Password are incorrect.
    bad_login -left-> initialNotRegistered : Go Back button
    bad_login: The user can press a button to go to register page if it is not already registered.
    bad_login : The user put the username and password to enter

    login -down-> RegisterScreen : Press button/link for registration
    bad_login -> RegisterScreen : Press button/link for registration
    RegisterScreen --> login : Go Back
    RegisterScreen -> RegisterScreen : Data are incorrect
    RegisterScreen : The user must put the NIF, name, contact info and description.
    RegisterScreen : There is a button to go back
    RegisterScreen : There is a button to register
}

RegisterScreen -down-> Registered : Registration done correctly.
login -down-> Registered : Login done correctly.

state Profile {

}

state Registered {
    state MainScreen
    [*] -right-> MainScreen
    MainScreen : The user must search and see publications
    MainScreen : The user can press a publication.
    MainScreen : The user can press the button of their profile.
    MainScreen : The down-menu is able as the user has already logged in

    MainScreen -down-> Profile : Press the button of user's profile
    Profile : Can see NIF, name, Contact Info and Description

    state Chat {

        [*] -> ListChat
        state ListChat {
            ListChat : A list of chats like Whatsapp, Telegram...
            ListChat : The user can search for a chat
            ListChat : The user can press a chat and the conversation screen will be opened
            LsitChat : In each item, the product only shows an small image if it has, the name, the owner, and the last message.
        }
        
        ListChat -right-> ConversationScreen : Press a conversation
        ConversationScreen -left-> ListChat : Go Back

        state ConversationScreen {
            ConversationScreen : Can send messages to another user
        }
    }

    MainScreen -down-> Chat : Chat button from down-menu.

    ConversationScreen -left-> Profile : Go to the other user profile

    state FormalOffer {
        [*] --> ListFormalOffer
        ListFormalOffer --> FormalOfferDetail : The user has pressed a formal offer.

        state ListFormalOffer {
            ListFormalOffer : A list of formal offers
            ListFormalOffer : The user can search for a formal offer.
            ListFormalOffer : The user can press a formal offer to see all the details.
            ListFormalOffer : Each item must have the name of the owner of the publication and product/service which has started the interaction.
        }

        state FormalOfferDetail {
            FormalOfferDetail : It must show:
            FormalOfferDetail : The name of the owner of the product/service which has started the interaction.
            FormalOfferDetail : The version of the formal offer
            FormalOfferDetail : The contract TextField
            FormalOfferDetail : The pdf attachment.
        }

        FormalOfferDetail --> ListFormalOffer : Go Back
    }

    MainScreen -down-> FormalOffer : FormalOffer button from down-menu.
    Chat -left-> FormalOffer : FormalOffer button from down-menu.
    FormalOffer -right-> Chat : Chat button from down-menu.


}

state PublicationDetail {
    PublicationDetail : It has to be shown the owner, title, description, latitude, longitude and tags.
    PublicationDetail : It has to be a link to the owner
    PublicationDetail : There will be a button to start the chat if only if the user is registered and logged.
}

PublicationDetail --> Profile : The user has press to the link of the owner
PublicationDetail --> ConversationScreen : A logged user can press a button to start the chat

initialNotRegistered -right-> PublicationDetail : Press a publication
MainScreen -right-> PublicationDetail : Press a publication

@enduml
